name: main
description: "Prescribr helps you to create reminders for your medications and reminds you when to take them."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  http: ^1.2.2
  flutter_dotenv: ^5.0.2
  firebase_core: ^3.14.0
  firebase_auth: ^5.3.3
  cloud_firestore: ^5.5.0
  provider: ^6.1.2
  firebase_messaging: ^15.1.5
  cupertino_icons: ^1.0.8
  intl: ^0.20.1
  timezone: ^0.10.0
  flutter_local_notifications: ^18.0.1
  font_awesome_flutter: ^10.5.0
  speech_to_text: ^7.0.0
  flutter_tts: ^3.5.3
  permission_handler: ^12.0.0+1



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  assets:
    - .env
    - assets/images/
  uses-material-design: true