// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjrD172MDoIxLY3CJbfiewgpdWgRgMCGE',
    appId: '1:458709881473:web:14a8fff97c6ab974493380',
    messagingSenderId: '458709881473',
    projectId: 'prescribr-sc',
    authDomain: 'prescribr-sc.firebaseapp.com',
    storageBucket: 'prescribr-sc.firebasestorage.app',
    measurementId: 'G-W7VSLFDR6F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjrD172MDoIxLY3CJbfiewgpdWgRgMCGE',
    appId: '1:458709881473:android:6a58eb088b40a653d8ecdf',
    messagingSenderId: '458709881473',
    projectId: 'prescribr-sc',
    storageBucket: 'prescribr-sc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjrD172MDoIxLY3CJbfiewgpdWgRgMCGE',
    appId: '1:458709881473:ios:512b1106b525e4bdd8ecdf',
    messagingSenderId: '458709881473',
    projectId: 'prescribr-sc',
    storageBucket: 'prescribr-sc.firebasestorage.app',
    iosBundleId: 'ca.prescribr.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCjrD172MDoIxLY3CJbfiewgpdWgRgMCGE',
    appId: '1:458709881473:ios:512b1106b525e4bdd8ecdf',
    messagingSenderId: '458709881473',
    projectId: 'prescribr-sc',
    storageBucket: 'prescribr-sc.firebasestorage.app',
    iosBundleId: 'ca.prescribr.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCjrD172MDoIxLY3CJbfiewgpdWgRgMCGE',
    appId: '1:458709881473:web:14a8fff97c6ab974493380',
    messagingSenderId: '458709881473',
    projectId: 'prescribr-sc',
    authDomain: 'prescribr-sc.firebaseapp.com',
    storageBucket: 'prescribr-sc.firebasestorage.app',
    measurementId: 'G-W7VSLFDR6F',
  );
}
